name: Windows

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Setup cl.exe
        uses: ilammy/msvc-dev-cmd@v1

      - name: Build
        shell: cmd
        run: |
          cd samples
          build_msvc.bat

      - name: Run Sample 1 Tests
        shell: cmd
        run: |
          cd samples
          sample1_unittest.exe